### ISSUE TITLE
Bibliographic Citations: typo

### ISSUE THREAD

**Issue by asbates** [software-tools-in-javascript/js4ds#213]
There is a typo in the 'Bibliographic Citations' section of the 'Manipulation Pages' chapter.

After the code chunk explaining the last `map` call the text states "(We haven’t shown the output in commas ...".
'commas' should be 'comments'.

I can make the edit but would need some help with the workflow. (where to make the edit, how to build everything, etc.)

**Comment by tobyhodges** [comment]
Thanks @asbates. I'll be happy to help you make this fix. You should be able to find the relevant sentence starting on line 706 of `pages.tex`. This is a mercifully straightforward part of the .tex file, so you should be able to edit the text without having to wrry about any LaTeX tags etc.

Looking at it again, I also think the end of the sentence would read better as

> [...] once we're showing strings containing HTML that contains strings.)

i.e. with "contains" rather than "contain." Perhaps you can also make that change while you're there?

No need to worry about building the new version - we'll take care of that, to incorporate recent changes from other PRs as well. For now, just making the change in the `pages.tex` will be great! 

Your contribution(s) will be acknowledged in the book's introduction.

**Comment by asbates** [comment]
Great! I'll make both changes then. 

Thanks for the help too. It will be a lot easier if I don't have to worry about building.

In the future, should I just submit a PR for something like this? Or should I open an issue first to get agreement from one of the authors?
